import type { Spec } from './snapshot.ts';

export interface MessageSpec {
  name: string;
  id: string;
  identifier: string;
  bodyTag: string;
  out: string;
  dir: string;
}

/** What a message's building blocks reach, split by kind of type. */
export interface Closure {
  components: string[];
  choices: string[];
  amounts: string[];
  simpleTypes: string[];
  externalSchemas: string[];
  codeSets: string[];
  /** Type names the snapshot does not define (should be empty). */
  unresolved: string[];
}

export type Kind = 'Component' | 'Choice' | 'Amount' | 'Codeset' | 'Attribute';

export function kindOf(spec: Spec, typeName: string): Kind | undefined {
  if (spec.components.has(typeName)) return 'Component';
  if (spec.choices.has(typeName)) return 'Choice';
  if (spec.amounts.has(typeName)) return 'Amount';
  if (spec.codeSets.has(typeName)) return 'Codeset';
  if (spec.simpleTypes.has(typeName) || spec.externalSchemas.has(typeName)) return 'Attribute';
  return undefined;
}

/** Everything reachable from a message's building blocks. */
export function closureOf(spec: Spec, message: MessageSpec): Closure {
  const msg = spec.messages.get(message.id);
  if (!msg) throw new Error(`message ${message.name} (${message.id}) is not in the snapshot`);
  if (msg.name !== message.name) throw new Error(`id ${message.id} is ${msg.name}, not ${message.name}`);
  const blocks = spec.blocks.get(message.name) ?? [];
  if (blocks.length === 0) throw new Error(`no building blocks for ${message.name}`);

  const out: Closure = { components: [], choices: [], amounts: [], simpleTypes: [], externalSchemas: [], codeSets: [], unresolved: [] };
  const seen = new Set<string>();
  const visit = (name: string): void => {
    if (seen.has(name)) return;
    seen.add(name);
    const k = kindOf(spec, name);
    if (k === undefined) return void out.unresolved.push(name);
    if (k === 'Component') {
      out.components.push(name);
      for (const e of spec.elements.get(name) ?? []) visit(e[4]!);
    } else if (k === 'Choice') {
      out.choices.push(name);
      for (const v of spec.variants.get(name) ?? []) visit(v[4]!);
    } else if (k === 'Amount') out.amounts.push(name);
    else if (k === 'Codeset') out.codeSets.push(name);
    else if (spec.externalSchemas.has(name)) out.externalSchemas.push(name);
    else out.simpleTypes.push(name);
  };
  for (const b of blocks) visit(b[4]!); // MSGBLOCK: messageName blockIsoId blockName xmlTag componentName ...
  return out;
}

const tsv = (cols: (string | number | undefined)[]): string => cols.map((c) => String(c ?? '').replace(/[\t\r\n]+/g, ' ')).join('\t');

/** The occurrence bounds as the generator reads them: blank min is 0, blank or `*` max is unbounded. */
const bounds = (min: string | undefined, max: string | undefined): [string, string] => [min === undefined || min === '' ? '0' : min, max === undefined || max === '' ? '*' : max];

export interface Written {
  complexTypes: string;
  snapshotRaw: string;
  choiceDefs: string;
  codeSetDefs: string;
}

/** The fixture files that come straight from the snapshot, for the types in `names` (new types only). */
export function writeStructure(spec: Spec, closure: Closure, isNew: (name: string) => boolean, isNewCodeSet: (name: string) => boolean = isNew): Written {
  const complex: string[] = [
    '# DATATYPE: DATATYPE name isoId kind status checksum definition; MEMBER: MEMBER parentName memberId memberName xmlTag kind dataTypeName minOccurs maxOccurs definition',
    '# Generated by tools/spec-extract from get_spec_snapshot (components + choices). Choice members are the snapshot\'s VARIANT rows.',
  ];
  const raw: string[] = ['# DATATYPE/MEMBER rows generated by tools/spec-extract from get_spec_snapshot. Choice variants are in complex-types.tsv and choice-defs.tsv.'];
  const choiceDefs: string[] = ['choice\tmemberId\tmemberName\ttext'];
  for (const name of closure.components.filter(isNew)) {
    const c = spec.components.get(name)!;
    const head = tsv(['DATATYPE', name, c.isoId, 'MessageComponent', c.status, c.checksum, c.definition]);
    const members = (spec.elements.get(name) ?? []).map((e) => {
      const [min, max] = bounds(e[5], e[6]);
      return tsv(['MEMBER', name, e[1], e[2], e[3], kindOf(spec, e[4]!), e[4], min, max, e[8]]);
    });
    complex.push(head, ...members);
    raw.push(head, ...members);
  }
  for (const name of closure.choices.filter(isNew)) {
    const c = spec.choices.get(name)!;
    const head = tsv(['DATATYPE', name, c.isoId, 'Choice', c.status, c.checksum, c.definition]);
    complex.push(head);
    raw.push(head);
    for (const v of spec.variants.get(name) ?? []) {
      // VARIANT: choiceName variantIsoId variantName xmlTag typeName status definition
      complex.push(tsv(['MEMBER', name, v[1], v[2], v[3], kindOf(spec, v[4]!), v[4], '1', '1', v[6]]));
      choiceDefs.push(tsv([name, v[1], v[2], v[6]]));
    }
  }
  const codeSetDefs = ['codeSet\tisoId\ttext', ...closure.codeSets.filter(isNewCodeSet).map((n) => tsv([n, spec.codeSets.get(n)!.isoId, spec.codeSets.get(n)!.definition]))];
  return { complexTypes: complex.join('\n') + '\n', snapshotRaw: raw.join('\n') + '\n', choiceDefs: choiceDefs.join('\n') + '\n', codeSetDefs: codeSetDefs.join('\n') + '\n' };
}

export interface MessageJson {
  identifier: string;
  name: string;
  namespace: string;
  bodyTag: string;
  out: string;
  isoId: string;
  definition: string;
  blocks: { name: string; isoId: string; xmlTag: string; type: string; min: number; max: number | null }[];
}

/** The message.json the generator reads: the message, its building blocks and its own definition text. */
export function messageJson(spec: Spec, m: MessageSpec): MessageJson {
  const msg = spec.messages.get(m.id);
  if (!msg) throw new Error(`message ${m.name} is not in the snapshot`);
  return {
    identifier: m.identifier,
    name: m.name,
    namespace: `urn:iso:std:iso:20022:tech:xsd:${m.identifier}`,
    bodyTag: m.bodyTag,
    out: m.out,
    isoId: m.id,
    definition: msg.definition,
    // MSGBLOCK: messageName blockIsoId blockName xmlTag componentName minOccurs maxOccurs status definition
    blocks: (spec.blocks.get(m.name) ?? []).map((b) => ({
      name: b[2]!,
      isoId: b[1]!,
      xmlTag: b[3]!,
      type: b[4]!,
      min: b[5] === undefined || b[5] === '' ? 0 : Number(b[5]),
      max: b[6] === undefined || b[6] === '' || b[6] === '*' ? null : Number(b[6]),
    })),
  };
}
