import type { DemoKey } from './demoText.ts';

/** French text for the Copy as menu, field modes and the words in what they copy. Machine-drafted; corrections welcome as GitHub issues. */
export const FR: Record<DemoKey, string> = {
  helpAreaTitle: 'Domaine métier',
  helpArea: 'ISO 20022 regroupe ses messages en domaines métier, tels que l’initiation de paiements (pain), la compensation et le règlement (pacs) et la gestion des distributeurs automatiques (caam). Choisissez un domaine pour voir ses messages.',
  helpMessageTitle: 'Message',
  helpMessage: 'Le message ISO 20022 à explorer, par son identifiant (domaine, fonction, variante et version). Choisissez-en un pour voir chaque élément qu’il peut contenir.',
  helpTypeTitle: 'Ce que montre le formulaire',
  helpType: 'Le message entier, ou seulement une partie. Choisissez une partie pour travailler dessus seule, comme la loupe à côté d’un élément.',
  helpDisplayTitle: 'Paramètres d’affichage',
  helpDisplay: 'Langue, thème clair ou sombre, taille du texte, densité, sortie en XML ou en JSON, et style du formulaire.',
  copyAs: 'Copier en tant que',
  copyAsTitle: 'Copier ce que le formulaire affiche actuellement, dans un format adapté à votre document ou à votre outil',
  copyAsMenu: 'Copier l’écran en tant que',
  optDefinitions: 'Inclure les définitions ISO 20022',
  optExcluded: 'Afficher les sections facultatives non incluses',
  optEmpty: 'Afficher les éléments facultatifs laissés vides',
  fmtWord: 'Word / texte enrichi',
  fmtWordDesc: 'Un tableau à coller dans Word, Outlook ou Google Docs',
  fmtMarkdown: 'Markdown',
  fmtMarkdownDesc: 'Un plan pour les wikis, GitHub, Confluence et les messageries',
  fmtSpreadsheet: 'Feuille de calcul',
  fmtSpreadsheetDesc: 'Des lignes à coller dans Excel ou Google Sheets : un dictionnaire de données de l’écran',
  fmtOutline: 'Plan en texte brut',
  fmtOutlineDesc: 'Une arborescence indentée de l’écran',
  fmtJson: 'JSON',
  fmtJsonDesc: 'La même structure, pour les outils',
  fmtImage: 'Image (PNG)',
  fmtImageDesc: 'Une image du formulaire, pour n’importe quel document',
  fmtFigma: 'SVG pour Figma',
  fmtFigmaDesc: 'À coller sur un canevas Figma (Ctrl/⌘+V) : calques modifiables nommés d’après les éléments ISO, dans un style de maquette filaire',
  fmtSvgFile: 'Fichier SVG',
  fmtSvgFileDesc: 'Le même dessin enregistré dans un fichier, à glisser dans Figma',
  saved: '{format} enregistré',
  include: 'Inclure',
  add: 'Ajouter',
  fieldModeTitle: 'Mode de champ de {element} : {mode}. Cliquez pour le modifier.',
  fieldModeMenu: 'Mode de champ',
  fieldModeTipTitle: 'Mode de champ : {mode}',
  fieldModeTip: 'La façon dont cet élément est présenté dans l’écran que vous concevez. Modifiable : le contrôle habituel. Libellé : affiché sous forme de texte, non modifiable. Masqué : non affiché, mais la valeur que vous laissez ici reste dans le message comme valeur par défaut. Cliquez pour choisir.',
  modeEditable: 'Modifiable',
  modeEditableDesc: 'Le contrôle habituel',
  modeLabel: 'Libellé',
  modeLabelDesc: 'Affiché sous forme de texte, non modifiable',
  modeHidden: 'Masqué',
  modeHiddenDesc: 'Non affiché ; la valeur que vous laissez ici reste dans le message',
  previewAsDesigned: 'Aperçu tel que conçu',
  previewTitle: 'Afficher les libellés sous forme de texte et omettre les éléments masqués, comme le ferait une application utilisant ces modes. Désactivé : tout reste modifiable et les autres éléments sont grisés.',
  copied: 'Copié en tant que {format}',
  copiedDownload: '{format} enregistré dans un fichier (ce navigateur n’a pas pu le copier)',
  copyFailed: 'Copie impossible : {why}',
  required: 'obligatoire',
  optional: 'facultatif',
  notIncluded: 'non inclus',
  empty: '(vide)',
  noneChosen: '(aucun choix)',
  items: '{n} éléments',
  oneItem: '1 élément',
  list: 'liste',
  error: 'Erreur',
  colElement: 'Élément',
  colRequired: 'Obligatoire',
  colValue: 'Valeur',
  colDefinition: 'Définition',
  colPath: 'Chemin',
  colIso: 'Élément ISO',
  colType: 'Type ISO',
  colKind: 'Nature',
  colStatus: 'Statut',
  colError: 'Erreur',
  colLevel: 'Niveau',
  colMode: 'Mode',
  modeWordLabel: 'libellé',
  modeWordHidden: 'masqué',
  statusFilled: 'renseigné',
  statusEmpty: 'vide',
  statusGroup: 'section',
  statusExcluded: 'non inclus',
  statusList: 'liste',
  statusChoice: 'choix',
  yes: 'oui',
  no: 'non',
};
