import type { DemoKey } from './demoText.ts';

/** German text for the Copy as menu, field modes and the words in what they copy. Machine-drafted; corrections welcome as GitHub issues. */
export const DE: Record<DemoKey, string> = {
  helpAreaTitle: 'Geschäftsbereich',
  helpArea: 'ISO 20022 gruppiert seine Nachrichten in Geschäftsbereiche, etwa Zahlungsinitiierung (pain), Clearing und Abwicklung (pacs) und Geldautomatenverwaltung (caam). Wählen Sie einen Bereich, um seine Nachrichten zu sehen.',
  helpMessageTitle: 'Nachricht',
  helpMessage: 'Die ISO-20022-Nachricht, die Sie erkunden möchten, nach ihrer Kennung (Bereich, Funktion, Variante und Version). Wählen Sie eine aus, um jedes Element zu sehen, das sie enthalten kann.',
  helpTypeTitle: 'Was das Formular zeigt',
  helpType: 'Die gesamte Nachricht oder nur ein Teil davon. Wählen Sie einen Teil, um ihn einzeln zu bearbeiten, genau wie mit der Lupe neben einem Element.',
  helpDisplayTitle: 'Anzeigeeinstellungen',
  helpDisplay: 'Sprache, helles oder dunkles Design, Textgröße, Dichte, ob die Ausgabe XML oder JSON ist, und der Stil des Formulars.',
  copyAs: 'Kopieren als',
  copyAsTitle: 'Kopiert, was das Formular gerade zeigt, in einem Format für Ihr Dokument oder Werkzeug',
  copyAsMenu: 'Bildschirm kopieren als',
  optDefinitions: 'ISO-20022-Definitionen einbeziehen',
  optExcluded: 'Optionale Abschnitte anzeigen, die nicht enthalten sind',
  optEmpty: 'Leere optionale Elemente anzeigen',
  fmtWord: 'Word / Rich Text',
  fmtWordDesc: 'Eine Tabelle zum Einfügen in Word, Outlook oder Google Docs',
  fmtMarkdown: 'Markdown',
  fmtMarkdownDesc: 'Eine Gliederung für Wikis, GitHub, Confluence und Chats',
  fmtSpreadsheet: 'Tabellenkalkulation',
  fmtSpreadsheetDesc: 'Zeilen zum Einfügen in Excel oder Google Sheets: ein Datenwörterbuch des Bildschirms',
  fmtOutline: 'Textgliederung',
  fmtOutlineDesc: 'Ein eingerückter Baum des Bildschirms',
  fmtJson: 'JSON',
  fmtJsonDesc: 'Dieselbe Struktur, für Werkzeuge',
  fmtImage: 'Bild (PNG)',
  fmtImageDesc: 'Ein Bild des Formulars, für jedes Dokument',
  fmtFigma: 'SVG für Figma',
  fmtFigmaDesc: 'In eine Figma-Zeichenfläche einfügen (Ctrl/⌘+V): bearbeitbare Ebenen, benannt nach den ISO-Elementen, im Wireframe-Stil',
  fmtSvgFile: 'SVG-Datei',
  fmtSvgFileDesc: 'Dieselbe Zeichnung als Datei gespeichert, zum Ziehen in Figma',
  saved: '{format} gespeichert',
  include: 'Einbeziehen',
  add: 'Hinzufügen',
  fieldModeTitle: 'Feldmodus von {element}: {mode}. Zum Ändern klicken.',
  fieldModeMenu: 'Feldmodus',
  fieldModeTipTitle: 'Feldmodus: {mode}',
  fieldModeTip: 'Wie dieses Element in dem Bildschirm dargestellt wird, den Sie gestalten. Bearbeitbar: das übliche Steuerelement. Beschriftung: als Text angezeigt, nicht bearbeitbar. Ausgeblendet: nicht angezeigt, aber der hier belassene Wert bleibt als Standardwert in der Nachricht. Zum Auswählen klicken.',
  modeEditable: 'Bearbeitbar',
  modeEditableDesc: 'Das übliche Steuerelement',
  modeLabel: 'Beschriftung',
  modeLabelDesc: 'Als Text angezeigt, nicht bearbeitbar',
  modeHidden: 'Ausgeblendet',
  modeHiddenDesc: 'Nicht angezeigt; der hier belassene Wert bleibt in der Nachricht',
  previewAsDesigned: 'Vorschau wie gestaltet',
  previewTitle: 'Beschriftungen als Text anzeigen und ausgeblendete Elemente weglassen, wie es eine Anwendung mit diesen Modi täte. Aus: Alles bleibt bearbeitbar und die übrigen sind schattiert.',
  copied: 'Kopiert als {format}',
  copiedDownload: '{format} als Datei gespeichert (dieser Browser konnte nicht kopieren)',
  copyFailed: 'Kopieren nicht möglich: {why}',
  required: 'erforderlich',
  optional: 'optional',
  notIncluded: 'nicht enthalten',
  empty: '(leer)',
  noneChosen: '(nichts gewählt)',
  items: '{n} Einträge',
  oneItem: '1 Eintrag',
  list: 'Liste',
  error: 'Fehler',
  colElement: 'Element',
  colRequired: 'Erforderlich',
  colValue: 'Wert',
  colDefinition: 'Definition',
  colPath: 'Pfad',
  colIso: 'ISO-Element',
  colType: 'ISO-Typ',
  colKind: 'Art',
  colStatus: 'Status',
  colError: 'Fehler',
  colLevel: 'Ebene',
  colMode: 'Modus',
  modeWordLabel: 'Beschriftung',
  modeWordHidden: 'ausgeblendet',
  statusFilled: 'ausgefüllt',
  statusEmpty: 'leer',
  statusGroup: 'Abschnitt',
  statusExcluded: 'nicht enthalten',
  statusList: 'Liste',
  statusChoice: 'Auswahl',
  yes: 'ja',
  no: 'nein',
};
