import type { DemoKey } from './demoText.ts';

/** Portuguese text for the Copy as menu, field modes and the words in what they copy. Machine-drafted; corrections welcome as GitHub issues. */
export const PT: Record<DemoKey, string> = {
  helpAreaTitle: 'Área de negócio',
  helpArea: 'A ISO 20022 agrupa as suas mensagens em áreas de negócio, como iniciação de pagamentos (pain), compensação e liquidação (pacs) e gestão de caixas automáticas (caam). Escolha uma área para ver as respetivas mensagens.',
  helpMessageTitle: 'Mensagem',
  helpMessage: 'A mensagem ISO 20022 que pretende explorar, pelo seu identificador (área, função, variante e versão). Escolha uma para ver todos os elementos que pode conter.',
  helpTypeTitle: 'O que o formulário mostra',
  helpType: 'A mensagem completa, ou apenas uma parte. Escolha uma parte para trabalhar só com ela, tal como a lupa junto de um elemento.',
  helpDisplayTitle: 'Definições de visualização',
  helpDisplay: 'Idioma, tema claro ou escuro, tamanho do texto, densidade, se a saída é XML ou JSON e o estilo do formulário.',
  copyAs: 'Copiar como',
  copyAsTitle: 'Copiar o que o formulário mostra agora, num formato para o seu documento ou ferramenta',
  copyAsMenu: 'Copiar o ecrã como',
  optDefinitions: 'Incluir as definições da ISO 20022',
  optExcluded: 'Mostrar as secções opcionais que não estão incluídas',
  optEmpty: 'Mostrar os elementos opcionais deixados vazios',
  fmtWord: 'Word / texto formatado',
  fmtWordDesc: 'Uma tabela que se cola no Word, Outlook ou Google Docs',
  fmtMarkdown: 'Markdown',
  fmtMarkdownDesc: 'Um esquema para wikis, GitHub, Confluence e conversas',
  fmtSpreadsheet: 'Folha de cálculo',
  fmtSpreadsheetDesc: 'Linhas que se colam no Excel ou Google Sheets: um dicionário de dados do ecrã',
  fmtOutline: 'Esquema de texto simples',
  fmtOutlineDesc: 'Uma árvore indentada do ecrã',
  fmtJson: 'JSON',
  fmtJsonDesc: 'A mesma estrutura, para ferramentas',
  fmtImage: 'Imagem (PNG)',
  fmtImageDesc: 'Uma imagem do formulário, para qualquer documento',
  fmtFigma: 'SVG para Figma',
  fmtFigmaDesc: 'Cole numa tela do Figma (Ctrl/⌘+V): camadas editáveis com os nomes dos elementos ISO, em estilo de esboço',
  fmtSvgFile: 'Ficheiro SVG',
  fmtSvgFileDesc: 'O mesmo desenho guardado como ficheiro, para arrastar para o Figma',
  saved: 'Guardado {format}',
  include: 'Incluir',
  add: 'Adicionar',
  fieldModeTitle: 'Modo do campo de {element}: {mode}. Clique para o alterar.',
  fieldModeMenu: 'Modo do campo',
  fieldModeTipTitle: 'Modo do campo: {mode}',
  fieldModeTip: 'Como este elemento é apresentado no ecrã que está a conceber. Editável: o controlo habitual. Etiqueta: mostrado como texto, não editável. Oculto: não é mostrado, mas o valor que aqui deixar permanece na mensagem como valor predefinido. Clique para escolher.',
  modeEditable: 'Editável',
  modeEditableDesc: 'O controlo habitual',
  modeLabel: 'Etiqueta',
  modeLabelDesc: 'Mostrado como texto, não editável',
  modeHidden: 'Oculto',
  modeHiddenDesc: 'Não é mostrado; o valor que aqui deixar permanece na mensagem',
  previewAsDesigned: 'Pré-visualizar como concebido',
  previewTitle: 'Mostrar as etiquetas como texto e omitir os elementos ocultos, como faria uma aplicação que use estes modos. Desativado: tudo permanece editável e os restantes aparecem sombreados.',
  copied: 'Copiado como {format}',
  copiedDownload: 'Guardado {format} como ficheiro (este navegador não o copiou)',
  copyFailed: 'Não foi possível copiar: {why}',
  required: 'obrigatório',
  optional: 'opcional',
  notIncluded: 'não incluído',
  empty: '(vazio)',
  noneChosen: '(nada escolhido)',
  items: '{n} itens',
  oneItem: '1 item',
  list: 'lista',
  error: 'Erro',
  colElement: 'Elemento',
  colRequired: 'Obrigatório',
  colValue: 'Valor',
  colDefinition: 'Definição',
  colPath: 'Caminho',
  colIso: 'Elemento ISO',
  colType: 'Tipo ISO',
  colKind: 'Tipo',
  colStatus: 'Estado',
  colError: 'Erro',
  colLevel: 'Nível',
  colMode: 'Modo',
  modeWordLabel: 'etiqueta',
  modeWordHidden: 'oculto',
  statusFilled: 'preenchido',
  statusEmpty: 'vazio',
  statusGroup: 'secção',
  statusExcluded: 'não incluído',
  statusList: 'lista',
  statusChoice: 'escolha',
  yes: 'sim',
  no: 'não',
};
