import { plural } from '@beneficial-strategies/iso20022-react-ui';
import type { PageMessages } from './messages.ts';

/** The demo page's text in Portuguese. Machine-drafted except English; corrections are welcome as GitHub issues. */
export const pagePt: PageMessages = {
  copyXml: 'Copiar XML',
  copied: 'Copiado',
  xml: 'XML',
  valid: 'válido',
  draft: ({ n }) => `rascunho — ${n} ${plural(n, 'problema', 'problemas')}`,
  doneEditing: 'Edição concluída',
  looksComplete: 'Parece completo.',
  problemsRemain: ({ n }) => (Number(n) === 1 ? 'Resta 1 problema.' : `Restam ${n} problemas.`),
  typeLabel: 'Tipo: ',
  typeSearch: 'Pesquisar tipos… (p. ex. PostalAddress, Party, Choice)',
  noMatch: 'Sem resultados',
  wholeMessage: '(mensagem completa, {id})',
  findType: 'Encontrar um tipo ISO 20022',
  title_form: 'ISO 20022 headless — com o nosso hook do TanStack Form',
  blurb_form:
    'O estado vem de @beneficial-strategies/iso20022-react (TanStack Form por baixo). A validação é o esquema Zod gerado; o hook devolve props para espalhar e não desenha nada — cada pixel aqui é marcação própria da demonstração.',
  title_zod: 'ISO 20022 headless — apenas Zod (sem biblioteca de formulários)',
  blurb_zod:
    'A mesma interface e o mesmo esquema Zod gerado, mas o estado do formulário são cerca de 80 linhas de React simples em src/useZodForm.ts — sem TanStack nem @beneficial-strategies/iso20022-react. Compare com a outra demonstração para ver o que o hook oferece.',
  rulesTitle: 'Regras de negócio ({status})',
  rulesNoneViolated: 'nenhuma violada',
  rulesViolated: ({ n }) => `${n} ${plural(n, 'violada', 'violadas')}`,
  ruleCounts: '{pass} {status_pass}, {fail} {status_fail}, {unsupported} {status_unsupported}, {prose} {status_prose}',
  status_pass: 'cumpridas',
  status_fail: 'violadas',
  status_unsupported: 'não verificáveis automaticamente',
  'status_prose-only': 'diretriz (não verificável por máquina)',
  display: 'Exibição ▾',
  displayDialog: 'Definições de exibição',
  theme: 'Tema',
  theme_system: 'Sistema',
  theme_light: 'Claro',
  theme_dark: 'Escuro',
  themeHint: 'Sistema segue a definição do seu sistema operativo.',
  textSize: 'Tamanho do texto',
  size_normal: 'Normal',
  size_large: 'Grande',
  size_xlarge: 'Muito grande',
  density: 'Densidade',
  density_comfortable: 'Confortável',
  density_compact: 'Compacta',
  skinLegend: 'Aparência do formulário (a parte headless)',
  skin_tailwind: 'Tailwind',
  skin_tailwind_desc: 'Estilo com classes utilitárias, com lista pendente acessível personalizada e balões de ajuda.',
  skin_plain: 'HTML simples',
  skin_plain_desc: 'HTML semântico sem estilo: fieldset, label, select nativo, details. Apenas os padrões do navegador.',
  language: 'Idioma',
  lang_auto: 'Automático (navegador)',
  reportWording: 'Comunicar um problema de redação',
  outputFormat: 'Formato de saída',
  format_xml: 'XML',
  format_json: 'JSON',
  formatHint: 'O JSON segue a sintaxe JSON da ISO 20022 (TSG, junho de 2025): etiquetas abreviadas, matrizes para elementos repetidos, valores como { amt, Ccy }.',
  copyJson: 'Copiar JSON',
  messageLabel: 'Mensagem',
  loading: 'A carregar…',
  settingsNote: 'As definições ficam no endereço da página, por isso uma ligação reproduz esta vista.',
  implement: 'Implementar!',
  implementTitle: 'Adicione isto à sua aplicação',
  implementIntro: 'Passos para adicionar {type} a uma aplicação existente. Copie, cole, execute.',
  implementUnpublished: 'Estes pacotes ainda não estão publicados no npm. Os comandos abaixo funcionarão quando estiverem.',
  stackLabel: 'A sua pilha de interface',
  stackReact: 'React',
  stackVue: 'Vue',
  stackSvelte: 'Svelte',
  stackOther: 'Angular ou TypeScript simples',
  stylingLabel: 'Estilo',
  stylingTailwind: 'A minha aplicação usa Tailwind CSS v4',
  extrasLabel: 'Também',
  extrasOutput: 'Obter saída em XML ou JSON ISO',
  pmLabel: 'Gestor de pacotes',
  close: 'Fechar',
  copy: 'Copiar',
  copiedShort: 'Copiado',
  stepInstall: '1. Instalar',
  stepComponent: '2. Adicionar o componente',
  stepUse: '3. Usar',
  stepStyles: 'Estilo (Tailwind)',
  stepCore: 'Validação, mensagens e saída',
  stepCoreVue: 'Vue: usar num componente',
  stepCoreSvelte: 'Svelte: usar num componente',
  noteRenderer: 'Ainda não existe um renderizador pronto para esta pilha. Obtém validação, mensagens e saída; desenha os campos e mostra cada mensagem junto ao respetivo campo.',
  noteLanguage: 'Para outro idioma, adicione locale="pt" (inglês, espanhol, francês, alemão e português estão incluídos).',
  noteTailwind: 'Adicione estas linhas à sua folha de estilos principal. O caminho para node_modules pode ser diferente no seu projeto. Sem Tailwind não precisa de CSS nenhum.',
  noteCoreFields: 'Os caminhos dos campos parecem-se com Parent.Child, e os itens de lista com Parent[0].Child.',
  pickStack: 'Escolha pelo menos uma pilha para ver os passos.',
  pasteXml: 'Colar XML',
  pasteJson: 'Colar JSON',
  paste: 'Colar',
  pasteNoData: 'A área de transferência não tem XML nem JSON para colar',
  pasteBlocked: 'O acesso à área de transferência está bloqueado para esta página. Permita-o no navegador para colar.',
  pasteUnknown: 'Lê a área de transferência ao clicar',
  pasteDone: '{format} carregado da área de transferência.',
  pasteDoneIssues: '{format} carregado da área de transferência, mas {n} não puderam ser colocados:',
  pasteSwitched: 'Mudou para {message} para corresponder ao espaço de nomes do XML colado.',
  pasteFailed: 'Nada foi colado.',
  pasteDismiss: 'Dispensar',
  pasteMoreIssues: 'e mais {n}',
  pasteError_empty: 'A área de transferência está vazia.',
  pasteError_not_xml_or_json: 'A área de transferência não contém XML nem JSON.',
  pasteError_unknown_namespace: 'Nenhuma mensagem desta biblioteca usa o espaço de nomes {namespace}.',
  pasteError_xml_syntax: 'O XML não está bem formado: {detail}',
  pasteError_json_syntax: 'O JSON não é válido: {detail}',
  pasteError_not_json_object: 'O JSON tem de ser um objeto.',
  pasteError_wrong_root: 'Esperava-se {expected} no topo, mas foi encontrado {found}.',
  pasteError_wrong_body: 'Esperava-se o elemento de mensagem {expected}, mas foi encontrado {found}.',
  pasteError_whole_message_for_part: 'Esta é uma mensagem completa, mas está a editar {typeName}. Selecione primeiro a mensagem completa.',
  pasteError_fragment_mismatch: 'Isto é um(a) {found}, mas está a editar {typeName}.',
  pasteError_clipboard_unreadable: 'Não foi possível ler a área de transferência. Permita o acesso e tente novamente.',
  pasteIssue_unknown_element: '{detail} não faz parte deste tipo (em {path}) e foi ignorado.',
  pasteIssue_duplicate_element: '{path} aparece mais de uma vez; foi usado o primeiro.',
  pasteIssue_multiple_choices: 'Mais de uma alternativa em {path} ({detail}); foi usada a primeira.',
  pasteIssue_unexpected_text: 'Texto inesperado em {path} foi ignorado.',
  pasteIssue_unexpected_element: '{detail} inesperado dentro de um valor simples em {path} foi ignorado.',
  loadFile: 'Carregar ficheiro…',
  saveXml: 'Guardar XML',
  saveJson: 'Guardar JSON',
  fileDone: '{format} carregado de {name}.',
  fileDoneIssues: '{format} carregado de {name}, mas {n} não puderam ser colocados:',
  fileFailed: 'Nada foi carregado.',
  fileError_empty: 'O ficheiro está vazio.',
  fileError_not_xml_or_json: 'O ficheiro não contém XML nem JSON.',
  fileError_unreadable: 'Não foi possível ler o ficheiro.',
  fileError_too_large: 'O ficheiro é demasiado grande (o limite é 20 MB).',
  stepServe: 'Ao implantar',
  noteServe: 'Os empacotadores dão a cada ficheiro gerado um nome baseado no seu conteúdo, por isso um ficheiro alterado recebe sempre um nome novo. Sirva esses ficheiros com um longo tempo de cache e os navegadores só os descarregam uma vez; ative também a compressão Brotli, se o seu alojamento a oferecer (cerca de 20 % menor que gzip).',
  areaLabel: 'Área',
  areaName_pain: 'Iniciação de pagamentos',
  areaDesc_pain: 'Mensagens que apoiam a iniciação de um pagamento pelo cliente ordenante junto de uma instituição financeira que gere uma conta de numerário, e a comunicação do seu estado.',
  areaName_pacs: 'Compensação e liquidação de pagamentos',
  areaDesc_pacs: 'Mensagens que apoiam os processos de compensação e liquidação de operações de pagamento entre instituições financeiras.',
  areaName_caam: 'Gestão de caixas automáticos',
  areaDesc_caam: 'Mensagens que apoiam os serviços de gestão de terminais relacionados com cartões entre uma caixa automática (ATM) e um adquirente.',
  xsdLabel: 'Validar XSD',
  xsdReady: 'Validar o texto da mensagem abaixo usando {location}',
  xsdReadyFile: 'Validar o texto da mensagem abaixo usando {file} (carregado do seu computador)',
  xsdLoading: 'A procurar o esquema em {url}…',
  xsdUnavailable: 'Não foi possível carregar o esquema de {url}. Clique com o botão direito para carregar um ficheiro local.',
  xsdNeedsXml: 'A validação XSD verifica XML. Mude a saída para XML para a usar.',
  xsdNotSchema: 'O ficheiro {file} não é um esquema XML (XSD).',
  xsdWrongSchema: 'O ficheiro {file} é um esquema para {found}, não para {expected}.',
  xsdReadFailed: 'Não foi possível ler o ficheiro {file}.',
  xsdPanelTitle: 'Erros de validação',
  xsdValid: 'Válido: o XML está em conformidade com o esquema.',
  xsdOneError: '1 erro',
  xsdErrors: '{n} erros',
  xsdChecking: 'A verificar…',
  xsdEngineFailed: 'Não foi possível executar o validador: {why}',
  xsdClose: 'Fechar erros de validação',
  xsdLine: 'Linha {n}',
  xsdLoadOther: 'Carregar outro ficheiro de esquema…',
  xsdSchemaFrom: 'Esquema: {source}',
  bannerTitle: 'Explorador de mensagens ISO 20022',
  logoAlt: 'Beneficial Strategies',
  logoLink: 'Página inicial da Beneficial Strategies (abre numa nova janela)',
  aboutOpen: 'Sobre esta ferramenta: o que pode fazer aqui',
  aboutTitle: 'Explore as mensagens ISO 20022',
  aboutIntro: 'Uma forma prática de ver o que realmente existe nas mensagens que bancos e sistemas de pagamento trocam, e de criar as suas.',
  aboutClose: 'Fechar',
  aboutStart: 'Começar a explorar',
  aboutExploreTitle: 'Explore o formato e o conteúdo',
  aboutExploreBody:
    'Escolha uma área e uma mensagem e veja todos os elementos que ela pode conter: como se chama, o que significa na definição oficial ISO 20022, que valores são permitidos e que regras de negócio ligam os campos. Passe o rato sobre o i junto a qualquer rótulo para ver a definição; «Ver especificação» abre a página oficial.',
  aboutCreateTitle: 'Crie uma nova mensagem',
  aboutCreateBody:
    'Preencha o formulário para criar uma mensagem de raiz. As suas entradas são verificadas à medida que escreve, e a mensagem final aparece ao lado do formulário em XML ou JSON ISO 20022.',
  aboutSaveTitle: 'Guarde e volte mais tarde',
  aboutSaveBody:
    'Guarde o que tem num ficheiro e carregue-o novamente quando quiser, ou cole uma mensagem que já tenha para a ver apresentada como formulário. Tudo fica no seu navegador.',
  aboutIllustrateTitle: 'Obtenha ilustrações para os seus documentos de análise',
  aboutIllustrateBody:
    'Aproxime apenas a parte de uma mensagem de que quer falar e depois tire uma captura de ecrã do formulário ou copie o seu XML ou JSON para o documento. As definições de exibição permitem escolher o idioma, claro ou escuro e o tamanho do texto.',
  aboutBuildTitle: 'Use estes controlos na sua própria aplicação',
  aboutBuildBody:
    'Gosta do aspeto e do comportamento do formulário? Escolha «Implementar!» por baixo do formulário para obter instruções passo a passo para adicionar os mesmos controlos à sua aplicação e estilizá-los à sua maneira.',
  aboutFootnote: 'As definições e as listas de códigos vêm do repositório ISO 20022. O texto em português é uma tradução automática e ainda não foi revisto.',
};
