import { plural } from '@beneficial-strategies/iso20022-react-ui';
import type { PageMessages } from './messages.ts';

/** The demo page's text in Spanish. Machine-drafted except English; corrections are welcome as GitHub issues. */
export const pageEs: PageMessages = {
  copyXml: 'Copiar XML',
  copied: 'Copiado',
  xml: 'XML',
  valid: 'válido',
  draft: ({ n }) => `borrador — ${n} ${plural(n, 'problema', 'problemas')}`,
  doneEditing: 'Edición terminada',
  looksComplete: 'Parece completo.',
  problemsRemain: ({ n }) => (Number(n) === 1 ? 'Queda 1 problema.' : `Quedan ${n} problemas.`),
  typeLabel: 'Tipo: ',
  typeSearch: 'Buscar tipos… (p. ej. PostalAddress, Party, Choice)',
  noMatch: 'Sin coincidencias',
  wholeMessage: '(mensaje completo, {id})',
  findType: 'Buscar un tipo de ISO 20022',
  title_form: 'ISO 20022 headless — con nuestro hook de TanStack Form',
  blurb_form:
    'El estado proviene de @beneficial-strategies/iso20022-react (TanStack Form por debajo). La validación es el esquema Zod generado; el hook devuelve props para propagar y no dibuja nada: todo el marcado de esta página es propio del demo.',
  title_zod: 'ISO 20022 headless — solo Zod (sin biblioteca de formularios)',
  blurb_zod:
    'La misma interfaz y el mismo esquema Zod generado, pero el estado del formulario son unas 80 líneas de React simple en src/useZodForm.ts: sin TanStack ni @beneficial-strategies/iso20022-react. Compárelo con el otro demo para ver qué aporta el hook.',
  rulesTitle: 'Reglas de negocio ({status})',
  rulesNoneViolated: 'ninguna infringida',
  rulesViolated: ({ n }) => `${n} ${plural(n, 'infringida', 'infringidas')}`,
  ruleCounts: '{pass} {status_pass}, {fail} {status_fail}, {unsupported} {status_unsupported}, {prose} {status_prose}',
  status_pass: 'cumplen',
  status_fail: 'infringidas',
  status_unsupported: 'no se pueden comprobar automáticamente',
  'status_prose-only': 'directrices (no verificables automáticamente)',
  display: 'Pantalla ▾',
  displayDialog: 'Ajustes de pantalla',
  theme: 'Tema',
  theme_system: 'Sistema',
  theme_light: 'Claro',
  theme_dark: 'Oscuro',
  themeHint: 'Sistema sigue la configuración de su sistema operativo.',
  textSize: 'Tamaño del texto',
  size_normal: 'Normal',
  size_large: 'Grande',
  size_xlarge: 'Muy grande',
  density: 'Densidad',
  density_comfortable: 'Cómoda',
  density_compact: 'Compacta',
  skinLegend: 'Aspecto del formulario (la parte «headless»)',
  skin_tailwind: 'Tailwind',
  skin_tailwind_desc: 'Estilos con clases de utilidad, con lista desplegable accesible personalizada y ayudas emergentes.',
  skin_plain: 'HTML simple',
  skin_plain_desc: 'HTML semántico sin estilos: fieldset, label, select nativo y details. Solo los valores predeterminados del navegador.',
  language: 'Idioma',
  lang_auto: 'Automático (navegador)',
  reportWording: 'Informar de un problema de redacción',
  outputFormat: 'Formato de salida',
  format_xml: 'XML',
  format_json: 'JSON',
  formatHint: 'JSON sigue la sintaxis JSON de ISO 20022 (TSG, junio de 2025): etiquetas abreviadas, matrices para elementos repetidos e importes como { amt, Ccy }.',
  copyJson: 'Copiar JSON',
  messageLabel: 'Mensaje',
  loading: 'Cargando…',
  settingsNote: 'Los ajustes se guardan en la dirección de la página, de modo que un enlace reproduce esta vista.',
  implement: '¡Implementar!',
  implementTitle: 'Añádalo a su aplicación',
  implementIntro: 'Pasos para añadir {type} a una aplicación existente. Copie, pegue y ejecute.',
  implementUnpublished: 'Estos paquetes aún no están publicados en npm. Los comandos de abajo son los que funcionarán cuando lo estén.',
  stackLabel: 'Su pila de interfaz',
  stackReact: 'React',
  stackVue: 'Vue',
  stackSvelte: 'Svelte',
  stackOther: 'Angular o TypeScript sin framework',
  stylingLabel: 'Estilos',
  stylingTailwind: 'Mi aplicación usa Tailwind CSS v4',
  extrasLabel: 'Además',
  extrasOutput: 'Obtener salida XML o JSON de ISO',
  pmLabel: 'Gestor de paquetes',
  close: 'Cerrar',
  copy: 'Copiar',
  copiedShort: 'Copiado',
  stepInstall: '1. Instalar',
  stepComponent: '2. Añadir el componente',
  stepUse: '3. Usarlo',
  stepStyles: 'Estilos (Tailwind)',
  stepCore: 'Validación, mensajes y salida',
  stepCoreVue: 'Vue: úselo en un componente',
  stepCoreSvelte: 'Svelte: úselo en un componente',
  noteRenderer: 'Todavía no hay un renderizador listo para esta pila. Esto le da validación, mensajes y salida; usted dibuja los campos y muestra cada mensaje junto a su campo.',
  noteLanguage: 'Para otro idioma, añada locale="es" (se incluyen inglés y español).',
  noteTailwind: 'Añada estas líneas a su hoja de estilos principal. La ruta a node_modules puede ser distinta en su proyecto. Sin Tailwind no necesita nada de CSS.',
  noteCoreFields: 'Las rutas de campo tienen la forma Padre.Hijo, y los elementos de lista Padre[0].Hijo.',
  pickStack: 'Elija al menos una pila para ver los pasos.',
  pasteXml: 'Pegar XML',
  pasteJson: 'Pegar JSON',
  paste: 'Pegar',
  pasteNoData: 'El portapapeles no contiene XML ni JSON para pegar',
  pasteBlocked: 'El acceso al portapapeles está bloqueado para esta página. Permítalo en el navegador para pegar.',
  pasteUnknown: 'Lee el portapapeles al hacer clic',
  pasteDone: 'Se cargó {format} desde el portapapeles.',
  pasteDoneIssues: 'Se cargó {format} desde el portapapeles, pero {n} no se pudieron colocar:',
  pasteSwitched: 'Se cambió a {message} para coincidir con el espacio de nombres del XML pegado.',
  pasteFailed: 'No se pegó nada.',
  pasteDismiss: 'Descartar',
  pasteMoreIssues: 'y {n} más',
  pasteError_empty: 'El portapapeles está vacío.',
  pasteError_not_xml_or_json: 'El portapapeles no contiene XML ni JSON.',
  pasteError_unknown_namespace: 'Ningún mensaje de esta biblioteca usa el espacio de nombres {namespace}.',
  pasteError_xml_syntax: 'El XML no está bien formado: {detail}',
  pasteError_json_syntax: 'El JSON no es válido: {detail}',
  pasteError_not_json_object: 'El JSON debe ser un objeto.',
  pasteError_wrong_root: 'Se esperaba {expected} en el nivel superior, pero se encontró {found}.',
  pasteError_wrong_body: 'Se esperaba el elemento de mensaje {expected}, pero se encontró {found}.',
  pasteError_whole_message_for_part: 'Es un mensaje completo, pero está editando {typeName}. Seleccione primero el mensaje completo.',
  pasteError_fragment_mismatch: 'Es un {found}, pero está editando {typeName}.',
  pasteError_clipboard_unreadable: 'No se pudo leer el portapapeles. Permita el acceso al portapapeles e inténtelo de nuevo.',
  pasteIssue_unknown_element: '{detail} no forma parte de este tipo (en {path}) y se omitió.',
  pasteIssue_duplicate_element: '{path} aparece más de una vez; se usó el primero.',
  pasteIssue_multiple_choices: 'Hay más de una alternativa en {path} ({detail}); se usó la primera.',
  pasteIssue_unexpected_text: 'Se ignoró texto inesperado en {path}.',
  pasteIssue_unexpected_element: 'Se ignoró {detail} inesperado dentro de un valor simple en {path}.',
  loadFile: 'Cargar archivo…',
  saveXml: 'Guardar XML',
  saveJson: 'Guardar JSON',
  fileDone: 'Se cargó {format} desde {name}.',
  fileDoneIssues: 'Se cargó {format} desde {name}, pero {n} no se pudieron colocar:',
  fileFailed: 'No se cargó nada.',
  fileError_empty: 'El archivo está vacío.',
  fileError_not_xml_or_json: 'El archivo no contiene XML ni JSON.',
  fileError_unreadable: 'No se pudo leer el archivo.',
  fileError_too_large: 'El archivo es demasiado grande (el límite es 20 MB).',
  stepServe: 'Al desplegar',
  noteServe: 'Los empaquetadores dan a cada archivo generado un nombre basado en su contenido, así que un archivo modificado siempre tiene un nombre nuevo. Sirva esos archivos con una vigencia de caché larga y los navegadores los descargarán una sola vez y los conservarán; active también la compresión Brotli si su servidor la ofrece (alrededor de un 20 % menor que gzip).',
  areaLabel: 'Área',
  areaName_pain: 'Iniciación de pagos',
  areaDesc_pain: 'Mensajes que respaldan la iniciación de un pago desde el cliente ordenante hacia una entidad financiera que administra una cuenta de efectivo, y la comunicación de su estado.',
  areaName_pacs: 'Compensación y liquidación de pagos',
  areaDesc_pacs: 'Mensajes que respaldan los procesos de compensación y liquidación de operaciones de pago entre entidades financieras.',
  areaName_caam: 'Gestión de cajeros automáticos',
  areaDesc_caam: 'Mensajes que respaldan los servicios de gestión de terminales relacionados con tarjetas entre un cajero automático (ATM) y un adquirente.',
  areaName_camt: 'Gestión de efectivo',
  areaDesc_camt: 'Mensajes que respaldan la comunicación y el aviso del lado de efectivo de cualquier operación financiera, incluidos los movimientos de efectivo, las operaciones y los saldos, además de cualquier excepción e investigación relacionada con operaciones de efectivo.',
  xsdLabel: 'Validar XSD',
  xsdReady: 'Validar el texto del mensaje de abajo con {location}',
  xsdReadyFile: 'Validar el texto del mensaje de abajo con {file} (cargado desde su equipo)',
  xsdLoading: 'Buscando el esquema en {url}…',
  xsdUnavailable: 'No se pudo cargar el esquema desde {url}. Haga clic con el botón derecho para cargarlo desde un archivo local.',
  xsdNeedsXml: 'La validación XSD comprueba XML. Cambie la salida a XML para usarla.',
  xsdNotSchema: 'El archivo {file} no es un esquema XML (XSD).',
  xsdWrongSchema: 'El archivo {file} es un esquema para {found}, no para {expected}.',
  xsdReadFailed: 'No se pudo leer el archivo {file}.',
  xsdPanelTitle: 'Errores de validación',
  xsdValid: 'Válido: el XML cumple el esquema.',
  xsdOneError: '1 error',
  xsdErrors: '{n} errores',
  xsdChecking: 'Comprobando…',
  xsdEngineFailed: 'No se pudo ejecutar el validador: {why}',
  xsdClose: 'Cerrar los errores de validación',
  xsdLine: 'Línea {n}',
  xsdLoadOther: 'Cargar otro archivo de esquema…',
  xsdSchemaFrom: 'Esquema: {source}',
  bannerTitle: 'Explorador de mensajes ISO 20022',
  logoAlt: 'Beneficial Strategies',
  logoLink: 'Página de inicio de Beneficial Strategies (se abre en una ventana nueva)',
  aboutOpen: 'Acerca de esta herramienta: qué puede hacer aquí',
  aboutTitle: 'Explore los mensajes ISO 20022',
  aboutIntro: 'Una forma práctica de ver qué contienen realmente los mensajes que intercambian bancos y sistemas de pago, y de crear los suyos.',
  aboutClose: 'Cerrar',
  aboutStart: 'Empezar a explorar',
  aboutExploreTitle: 'Explore el formato y el contenido',
  aboutExploreBody:
    'Elija un área y un mensaje, y vea cada elemento que puede contener: cómo se llama, qué significa según la definición oficial de ISO 20022, qué valores admite y qué reglas de negocio relacionan unos campos con otros. Pase el cursor sobre la i junto a cualquier etiqueta para ver su definición; Ver especificación abre la página oficial.',
  aboutCreateTitle: 'Cree un mensaje nuevo',
  aboutCreateBody:
    'Complete el formulario para construir un mensaje desde cero. Sus datos se validan mientras escribe, y el mensaje terminado aparece junto al formulario como XML o JSON de ISO 20022.',
  aboutSaveTitle: 'Guárdelo y continúe más tarde',
  aboutSaveBody:
    'Guarde lo que tenga en un archivo y cárguelo de nuevo cuando quiera, o pegue un mensaje que ya tenga para verlo como formulario. Todo permanece en su navegador.',
  aboutIllustrateTitle: 'Obtenga ilustraciones para sus documentos de análisis',
  aboutIllustrateBody:
    'Amplíe solo la parte del mensaje de la que quiere hablar y haga una captura de pantalla del formulario, o copie su XML o JSON en su documento. En Pantalla puede elegir el idioma, el modo claro u oscuro y el tamaño del texto.',
  aboutBuildTitle: 'Use estos controles en su propia aplicación',
  aboutBuildBody:
    '¿Le gusta cómo se ve y se comporta el formulario? Elija Implement! debajo del formulario para obtener instrucciones paso a paso y añadir los mismos controles a su aplicación, con su propio estilo.',
  aboutFootnote: 'Las definiciones y las listas de códigos provienen del repositorio de ISO 20022. El texto en español es una traducción automática y aún no está revisado.',
};
