import type { PageMessages } from './messages.ts';

/** The demo page's text in English. Machine-drafted except English; corrections are welcome as GitHub issues. */
export const pageEn: PageMessages = {
  copyXml: 'Copy XML',
  copied: 'Copied',
  xml: 'XML',
  valid: 'valid',
  draft: 'draft — {n} problem(s)',
  doneEditing: 'Done editing',
  looksComplete: 'Looks complete.',
  problemsRemain: '{n} problem(s) remain.',
  typeLabel: 'Type: ',
  typeSearch: 'Search types… (e.g. PostalAddress, Party, Choice)',
  noMatch: 'No match',
  wholeMessage: '(whole message, {id})',
  findType: 'Find an ISO 20022 type',
  title_form: 'ISO 20022 headless — with our TanStack Form hook',
  blurb_form:
    'State comes from @beneficial-strategies/iso20022-react (TanStack Form underneath). Validation is the generated Zod schema; the hook returns props to spread and renders nothing — every pixel here is the demo\'s own markup.',
  title_zod: 'ISO 20022 headless — Zod only (no form library)',
  blurb_zod:
    'Same UI, same generated Zod schema, but form state is ~80 lines of plain React in src/useZodForm.ts — no TanStack, no @beneficial-strategies/iso20022-react. Compare with the other demo to see what the hook buys you.',
  rulesTitle: 'Business rules ({status})',
  rulesNoneViolated: 'none violated',
  rulesViolated: '{n} violated',
  ruleCounts: '{pass} {status_pass}, {fail} {status_fail}, {unsupported} {status_unsupported}, {prose} {status_prose}',
  status_pass: 'passes',
  status_fail: 'violated',
  status_unsupported: 'cannot be checked automatically',
  'status_prose-only': 'guideline (not machine-checkable)',
  display: 'Display ▾',
  displayDialog: 'Display settings',
  theme: 'Theme',
  theme_system: 'System',
  theme_light: 'Light',
  theme_dark: 'Dark',
  themeHint: 'System follows your operating system setting.',
  textSize: 'Text size',
  size_normal: 'Normal',
  size_large: 'Large',
  size_xlarge: 'Extra large',
  density: 'Density',
  density_comfortable: 'Comfortable',
  density_compact: 'Compact',
  skinLegend: 'Form skin (the headless part)',
  skin_tailwind: 'Tailwind',
  skin_tailwind_desc: 'Utility-class styling with a custom accessible dropdown and help popovers.',
  skin_plain: 'Plain HTML',
  skin_plain_desc: 'Unstyled semantic HTML: fieldset, label, native select, details. Browser defaults only.',
  language: 'Language',
  lang_auto: 'Automatic (browser)',
  reportWording: 'Report a wording problem',
  outputFormat: 'Output format',
  format_xml: 'XML',
  format_json: 'JSON',
  formatHint: 'JSON follows the ISO 20022 JSON syntax (TSG, June 2025): abbreviated tags, arrays for repeating elements, amounts as { amt, Ccy }.',
  copyJson: 'Copy JSON',
  messageLabel: 'Message',
  loading: 'Loading…',
  settingsNote: 'Settings are kept in the page address, so a link reproduces this view.',
  implement: 'Implement!',
  implementTitle: 'Add this to your app',
  implementIntro: 'Steps to add {type} to an existing app. Copy, paste, run.',
  implementUnpublished: 'These packages are not published to npm yet. The commands below are what will work once they are.',
  stackLabel: 'Your UI stack',
  stackReact: 'React',
  stackVue: 'Vue',
  stackSvelte: 'Svelte',
  stackOther: 'Angular or plain TypeScript',
  stylingLabel: 'Styling',
  stylingTailwind: 'My app uses Tailwind CSS v4',
  extrasLabel: 'Also',
  extrasOutput: 'Get XML or ISO JSON output',
  pmLabel: 'Package manager',
  close: 'Close',
  copy: 'Copy',
  copiedShort: 'Copied',
  stepInstall: '1. Install',
  stepComponent: '2. Add the component',
  stepUse: '3. Use it',
  stepStyles: 'Styling (Tailwind)',
  stepCore: 'Validation, messages and output',
  stepCoreVue: 'Vue: use it in a component',
  stepCoreSvelte: 'Svelte: use it in a component',
  noteRenderer: 'There is no ready-made renderer for this stack yet. This gives you validation, messages and output; you draw the inputs and show each message next to its field.',
  noteLanguage: 'For another language, add locale="es" (English and Spanish are included).',
  noteTailwind: 'Add these lines to your main stylesheet. The path to node_modules may differ in your project. Without Tailwind you need no CSS at all.',
  noteCoreFields: 'Field paths look like Parent.Child, and list items like Parent[0].Child.',
  pickStack: 'Pick at least one stack to see the steps.',
  pasteXml: 'Paste XML',
  pasteJson: 'Paste JSON',
  paste: 'Paste',
  pasteNoData: 'The clipboard has no XML or JSON to paste',
  pasteBlocked: 'Clipboard access is blocked for this page. Allow it in the browser to paste.',
  pasteUnknown: 'Reads the clipboard when you click',
  pasteDone: 'Loaded {format} from the clipboard.',
  pasteDoneIssues: 'Loaded {format} from the clipboard, but {n} could not be placed:',
  pasteSwitched: 'Switched to {message} to match the namespace of the pasted XML.',
  pasteFailed: 'Nothing was pasted.',
  pasteDismiss: 'Dismiss',
  pasteMoreIssues: 'and {n} more',
  pasteError_empty: 'The clipboard is empty.',
  pasteError_not_xml_or_json: 'The clipboard does not contain XML or JSON.',
  pasteError_unknown_namespace: 'No message in this library uses the namespace {namespace}.',
  pasteError_xml_syntax: 'The XML is not well-formed: {detail}',
  pasteError_json_syntax: 'The JSON is not valid: {detail}',
  pasteError_not_json_object: 'The JSON must be an object.',
  pasteError_wrong_root: 'Expected {expected} at the top, but found {found}.',
  pasteError_wrong_body: 'Expected the {expected} message element, but found {found}.',
  pasteError_whole_message_for_part: 'This is a whole message, but you are editing {typeName}. Select the whole message first.',
  pasteError_fragment_mismatch: 'This is a {found}, but you are editing {typeName}.',
  pasteError_clipboard_unreadable: 'The clipboard could not be read. Allow clipboard access and try again.',
  pasteIssue_unknown_element: '{detail} is not part of this type (at {path}) and was skipped.',
  pasteIssue_duplicate_element: '{path} appears more than once; the first was used.',
  pasteIssue_multiple_choices: 'More than one alternative at {path} ({detail}); the first was used.',
  pasteIssue_unexpected_text: 'Unexpected text at {path} was ignored.',
  pasteIssue_unexpected_element: 'Unexpected {detail} inside a single value at {path} was ignored.',
  loadFile: 'Load file…',
  saveXml: 'Save XML',
  saveJson: 'Save JSON',
  fileDone: 'Loaded {format} from {name}.',
  fileDoneIssues: 'Loaded {format} from {name}, but {n} could not be placed:',
  fileFailed: 'Nothing was loaded.',
  fileError_empty: 'The file is empty.',
  fileError_not_xml_or_json: 'The file does not contain XML or JSON.',
  fileError_unreadable: 'The file could not be read.',
  fileError_too_large: 'The file is too large (the limit is 20 MB).',
  stepServe: 'When you deploy',
  noteServe: 'Bundlers name each built file after its content, so a changed file always gets a new name. Serve those files with a long cache lifetime and browsers download them once, then keep them; also turn on Brotli compression if your host offers it (about 20% smaller than gzip).',
  areaLabel: 'Area',
  areaName_pain: 'Payments Initiation',
  areaDesc_pain: 'Messages that support the initiation of a payment from the ordering customer to a financial institution that services a cash account and reporting its status.',
  areaName_pacs: 'Payments Clearing and Settlement',
  areaDesc_pacs: 'Messages that support the clearing and settlement processes for payment transactions between financial institutions.',
  areaName_caam: 'ATM Management',
  areaDesc_caam: 'Messages that support card related terminal management services between an Automated Teller Machine (ATM) and an Acquirer.',
  areaName_camt: 'Cash Management',
  areaDesc_camt: 'Messages that support the reporting and advicing of the cash side of any financial transactions, including cash movements, transactions and balances, plus any exceptions and investigations related to cash transactions.',
  xsdLabel: 'XSD Validate',
  xsdReady: 'Validate the text of the message below using {location}',
  xsdReadyFile: 'Validate the text of the message below using {file} (loaded from your computer)',
  xsdLoading: 'Looking for the schema at {url}…',
  xsdUnavailable: 'Could not load schema from {url}. Right-click to load from local file.',
  xsdNeedsXml: 'XSD validation checks XML. Switch the output to XML to use it.',
  xsdNotSchema: 'The file {file} is not an XML Schema (XSD).',
  xsdWrongSchema: 'The file {file} is a schema for {found}, not for {expected}.',
  xsdReadFailed: 'The file {file} could not be read.',
  xsdPanelTitle: 'Validation Errors',
  xsdValid: 'Valid: the XML conforms to the schema.',
  xsdOneError: '1 error',
  xsdErrors: '{n} errors',
  xsdChecking: 'Checking…',
  xsdEngineFailed: 'The validator could not run: {why}',
  xsdClose: 'Close validation errors',
  xsdLine: 'Line {n}',
  xsdLoadOther: 'Load a different schema file…',
  xsdSchemaFrom: 'Schema: {source}',
  bannerTitle: 'ISO 20022 Message Explorer',
  logoAlt: 'Beneficial Strategies',
  logoLink: 'Beneficial Strategies home page (opens in a new window)',
  aboutOpen: 'About this tool: what you can do here',
  aboutTitle: 'Explore ISO 20022 messages',
  aboutIntro: 'A hands-on way to see what is really inside the messages banks and payment systems exchange, and to build your own.',
  aboutClose: 'Close',
  aboutStart: 'Start exploring',
  aboutExploreTitle: 'Explore the format and the content',
  aboutExploreBody:
    'Pick an area and a message, and see every element it can hold: what it is called, what it means in the official ISO 20022 definition, which values are allowed, and which business rules tie fields together. Hover the i next to any label for its definition; View Specification opens the official page.',
  aboutCreateTitle: 'Create a new message',
  aboutCreateBody:
    'Fill in the form to build a message from scratch. Your entries are checked as you type, and the finished message appears beside the form as XML or ISO 20022 JSON.',
  aboutSaveTitle: 'Save it and come back later',
  aboutSaveBody:
    'Save what you have to a file and load it again whenever you like, or paste a message you already have to see it laid out as a form. Everything stays in your browser.',
  aboutIllustrateTitle: 'Grab illustrations for your analysis documents',
  aboutIllustrateBody:
    'Zoom into just the part of a message you want to talk about, then take a screenshot of the form or copy its XML or JSON into your document. Display settings let you choose language, light or dark, and text size.',
  aboutBuildTitle: 'Use these controls in your own application',
  aboutBuildBody:
    'Like how the form looks and behaves? Choose Implement! under the form for step-by-step instructions to add the same controls to your own application and style them your way.',
  aboutFootnote: 'Definitions and code lists come from the ISO 20022 repository. Spanish text is machine-translated and not yet reviewed.',
};
