import { plural } from '@beneficial-strategies/iso20022-react-ui';
import type { PageMessages } from './messages.ts';

/** The demo page's text in German. Machine-drafted except English; corrections are welcome as GitHub issues. */
export const pageDe: PageMessages = {
  copyXml: 'XML kopieren',
  copied: 'Kopiert',
  xml: 'XML',
  valid: 'gültig',
  draft: ({ n }) => `Entwurf — ${n} ${plural(n, 'Problem', 'Probleme')}`,
  doneEditing: 'Bearbeitung abgeschlossen',
  looksComplete: 'Sieht vollständig aus.',
  problemsRemain: ({ n }) => (Number(n) === 1 ? 'Es bleibt 1 Problem.' : `Es bleiben ${n} Probleme.`),
  typeLabel: 'Typ: ',
  typeSearch: 'Typen suchen… (z. B. PostalAddress, Party, Choice)',
  noMatch: 'Keine Treffer',
  wholeMessage: '(gesamte Nachricht, {id})',
  findType: 'ISO-20022-Typ suchen',
  title_form: 'ISO 20022 headless — mit unserem TanStack-Form-Hook',
  blurb_form:
    'Der Zustand stammt aus @beneficial-strategies/iso20022-react (darunter TanStack Form). Die Validierung ist das generierte Zod-Schema; der Hook liefert Props zum Weiterreichen und zeichnet nichts — jedes Pixel hier ist das eigene Markup der Demo.',
  title_zod: 'ISO 20022 headless — nur Zod (keine Formularbibliothek)',
  blurb_zod:
    'Dieselbe Oberfläche, dasselbe generierte Zod-Schema, aber der Formularzustand besteht aus ~80 Zeilen reinem React in src/useZodForm.ts — weder TanStack noch @beneficial-strategies/iso20022-react. Vergleichen Sie mit der anderen Demo, um zu sehen, was der Hook bringt.',
  rulesTitle: 'Geschäftsregeln ({status})',
  rulesNoneViolated: 'keine verletzt',
  rulesViolated: '{n} verletzt',
  ruleCounts: '{pass} {status_pass}, {fail} {status_fail}, {unsupported} {status_unsupported}, {prose} {status_prose}',
  status_pass: 'erfüllt',
  status_fail: 'verletzt',
  status_unsupported: 'nicht automatisch prüfbar',
  'status_prose-only': 'Richtlinie (nicht maschinell prüfbar)',
  display: 'Anzeige ▾',
  displayDialog: 'Anzeigeeinstellungen',
  theme: 'Design',
  theme_system: 'System',
  theme_light: 'Hell',
  theme_dark: 'Dunkel',
  themeHint: 'System folgt der Einstellung Ihres Betriebssystems.',
  textSize: 'Textgröße',
  size_normal: 'Normal',
  size_large: 'Groß',
  size_xlarge: 'Sehr groß',
  density: 'Dichte',
  density_comfortable: 'Komfortabel',
  density_compact: 'Kompakt',
  skinLegend: 'Formular-Skin (der Headless-Teil)',
  skin_tailwind: 'Tailwind',
  skin_tailwind_desc: 'Styling mit Utility-Klassen, mit eigenem barrierefreiem Dropdown und Hilfe-Popovers.',
  skin_plain: 'Schlichtes HTML',
  skin_plain_desc: 'Ungestyltes semantisches HTML: fieldset, label, natives select, details. Nur Browser-Standards.',
  language: 'Sprache',
  lang_auto: 'Automatisch (Browser)',
  reportWording: 'Ein Formulierungsproblem melden',
  outputFormat: 'Ausgabeformat',
  format_xml: 'XML',
  format_json: 'JSON',
  formatHint: 'JSON folgt der ISO-20022-JSON-Syntax (TSG, Juni 2025): abgekürzte Tags, Arrays für wiederholte Elemente, Beträge als { amt, Ccy }.',
  copyJson: 'JSON kopieren',
  messageLabel: 'Nachricht',
  loading: 'Wird geladen…',
  settingsNote: 'Die Einstellungen stehen in der Seitenadresse, sodass ein Link diese Ansicht wiederherstellt.',
  implement: 'Umsetzen!',
  implementTitle: 'In Ihre App einbauen',
  implementIntro: 'Schritte, um {type} in eine bestehende App einzubauen. Kopieren, einfügen, ausführen.',
  implementUnpublished: 'Diese Pakete sind noch nicht auf npm veröffentlicht. Die folgenden Befehle funktionieren, sobald sie es sind.',
  stackLabel: 'Ihr UI-Stack',
  stackReact: 'React',
  stackVue: 'Vue',
  stackSvelte: 'Svelte',
  stackOther: 'Angular oder reines TypeScript',
  stylingLabel: 'Styling',
  stylingTailwind: 'Meine App verwendet Tailwind CSS v4',
  extrasLabel: 'Außerdem',
  extrasOutput: 'XML- oder ISO-JSON-Ausgabe erhalten',
  pmLabel: 'Paketmanager',
  close: 'Schließen',
  copy: 'Kopieren',
  copiedShort: 'Kopiert',
  stepInstall: '1. Installieren',
  stepComponent: '2. Komponente hinzufügen',
  stepUse: '3. Verwenden',
  stepStyles: 'Styling (Tailwind)',
  stepCore: 'Validierung, Meldungen und Ausgabe',
  stepCoreVue: 'Vue: in einer Komponente verwenden',
  stepCoreSvelte: 'Svelte: in einer Komponente verwenden',
  noteRenderer: 'Für diesen Stack gibt es noch keinen fertigen Renderer. Sie erhalten Validierung, Meldungen und Ausgabe; die Eingabefelder zeichnen Sie selbst und zeigen jede Meldung neben ihrem Feld an.',
  noteLanguage: 'Für eine andere Sprache fügen Sie locale="de" hinzu (Englisch, Spanisch, Französisch, Deutsch und Portugiesisch sind enthalten).',
  noteTailwind: 'Fügen Sie diese Zeilen Ihrem Haupt-Stylesheet hinzu. Der Pfad zu node_modules kann in Ihrem Projekt abweichen. Ohne Tailwind brauchen Sie überhaupt kein CSS.',
  noteCoreFields: 'Feldpfade sehen aus wie Parent.Child, Listeneinträge wie Parent[0].Child.',
  pickStack: 'Wählen Sie mindestens einen Stack, um die Schritte zu sehen.',
  pasteXml: 'XML einfügen',
  pasteJson: 'JSON einfügen',
  paste: 'Einfügen',
  pasteNoData: 'Die Zwischenablage enthält kein XML oder JSON zum Einfügen',
  pasteBlocked: 'Der Zugriff auf die Zwischenablage ist für diese Seite blockiert. Erlauben Sie ihn im Browser, um einzufügen.',
  pasteUnknown: 'Liest die Zwischenablage beim Klicken',
  pasteDone: '{format} aus der Zwischenablage geladen.',
  pasteDoneIssues: '{format} aus der Zwischenablage geladen, aber {n} konnten nicht zugeordnet werden:',
  pasteSwitched: 'Zu {message} gewechselt, passend zum Namensraum des eingefügten XML.',
  pasteFailed: 'Es wurde nichts eingefügt.',
  pasteDismiss: 'Ausblenden',
  pasteMoreIssues: 'und {n} weitere',
  pasteError_empty: 'Die Zwischenablage ist leer.',
  pasteError_not_xml_or_json: 'Die Zwischenablage enthält weder XML noch JSON.',
  pasteError_unknown_namespace: 'Keine Nachricht dieser Bibliothek verwendet den Namensraum {namespace}.',
  pasteError_xml_syntax: 'Das XML ist nicht wohlgeformt: {detail}',
  pasteError_json_syntax: 'Das JSON ist ungültig: {detail}',
  pasteError_not_json_object: 'Das JSON muss ein Objekt sein.',
  pasteError_wrong_root: 'Erwartet wurde {expected} an oberster Stelle, gefunden wurde {found}.',
  pasteError_wrong_body: 'Erwartet wurde das Nachrichtenelement {expected}, gefunden wurde {found}.',
  pasteError_whole_message_for_part: 'Dies ist eine gesamte Nachricht, Sie bearbeiten aber {typeName}. Wählen Sie zuerst die gesamte Nachricht aus.',
  pasteError_fragment_mismatch: 'Dies ist ein {found}, Sie bearbeiten aber {typeName}.',
  pasteError_clipboard_unreadable: 'Die Zwischenablage konnte nicht gelesen werden. Erlauben Sie den Zugriff und versuchen Sie es erneut.',
  pasteIssue_unknown_element: '{detail} gehört nicht zu diesem Typ (bei {path}) und wurde übersprungen.',
  pasteIssue_duplicate_element: '{path} kommt mehrfach vor; das erste wurde verwendet.',
  pasteIssue_multiple_choices: 'Mehr als eine Alternative bei {path} ({detail}); die erste wurde verwendet.',
  pasteIssue_unexpected_text: 'Unerwarteter Text bei {path} wurde ignoriert.',
  pasteIssue_unexpected_element: 'Unerwartetes {detail} innerhalb eines Einzelwerts bei {path} wurde ignoriert.',
  loadFile: 'Datei laden…',
  saveXml: 'XML speichern',
  saveJson: 'JSON speichern',
  fileDone: '{format} aus {name} geladen.',
  fileDoneIssues: '{format} aus {name} geladen, aber {n} konnten nicht zugeordnet werden:',
  fileFailed: 'Es wurde nichts geladen.',
  fileError_empty: 'Die Datei ist leer.',
  fileError_not_xml_or_json: 'Die Datei enthält weder XML noch JSON.',
  fileError_unreadable: 'Die Datei konnte nicht gelesen werden.',
  fileError_too_large: 'Die Datei ist zu groß (das Limit beträgt 20 MB).',
  stepServe: 'Beim Deployment',
  noteServe: 'Bundler benennen jede erzeugte Datei nach ihrem Inhalt, sodass eine geänderte Datei immer einen neuen Namen erhält. Liefern Sie diese Dateien mit langer Cache-Lebensdauer aus, dann laden Browser sie nur einmal herunter; aktivieren Sie außerdem Brotli-Kompression, falls Ihr Host sie anbietet (etwa 20 % kleiner als gzip).',
  areaLabel: 'Bereich',
  areaName_pain: 'Zahlungsinitiierung',
  areaDesc_pain: 'Nachrichten, die die Initiierung einer Zahlung durch den Auftraggeber bei einem Finanzinstitut, das ein Geldkonto führt, sowie die Meldung ihres Status unterstützen.',
  areaName_pacs: 'Zahlungsclearing und -abwicklung',
  areaDesc_pacs: 'Nachrichten, die die Clearing- und Abwicklungsprozesse für Zahlungsvorgänge zwischen Finanzinstituten unterstützen.',
  areaName_caam: 'Geldautomatenverwaltung',
  areaDesc_caam: 'Nachrichten, die kartenbezogene Terminalverwaltungsdienste zwischen einem Geldautomaten (ATM) und einem Acquirer unterstützen.',
  xsdLabel: 'XSD prüfen',
  xsdReady: 'Den Text der Nachricht unten mit {location} prüfen',
  xsdReadyFile: 'Den Text der Nachricht unten mit {file} prüfen (von Ihrem Computer geladen)',
  xsdLoading: 'Schema wird unter {url} gesucht…',
  xsdUnavailable: 'Das Schema konnte nicht von {url} geladen werden. Rechtsklick, um eine lokale Datei zu laden.',
  xsdNeedsXml: 'Die XSD-Prüfung prüft XML. Stellen Sie die Ausgabe auf XML um.',
  xsdNotSchema: 'Die Datei {file} ist kein XML-Schema (XSD).',
  xsdWrongSchema: 'Die Datei {file} ist ein Schema für {found}, nicht für {expected}.',
  xsdReadFailed: 'Die Datei {file} konnte nicht gelesen werden.',
  xsdPanelTitle: 'Validierungsfehler',
  xsdValid: 'Gültig: Das XML entspricht dem Schema.',
  xsdOneError: '1 Fehler',
  xsdErrors: '{n} Fehler',
  xsdChecking: 'Wird geprüft…',
  xsdEngineFailed: 'Der Validator konnte nicht ausgeführt werden: {why}',
  xsdClose: 'Validierungsfehler schließen',
  xsdLine: 'Zeile {n}',
  xsdLoadOther: 'Eine andere Schemadatei laden…',
  xsdSchemaFrom: 'Schema: {source}',
  bannerTitle: 'ISO 20022 Message Explorer',
  logoAlt: 'Beneficial Strategies',
  logoLink: 'Startseite von Beneficial Strategies (öffnet in einem neuen Fenster)',
  aboutOpen: 'Über dieses Werkzeug: was Sie hier tun können',
  aboutTitle: 'ISO-20022-Nachrichten erkunden',
  aboutIntro: 'Ein praktischer Weg, zu sehen, was wirklich in den Nachrichten steckt, die Banken und Zahlungssysteme austauschen, und eigene zu erstellen.',
  aboutClose: 'Schließen',
  aboutStart: 'Mit dem Erkunden beginnen',
  aboutExploreTitle: 'Format und Inhalt erkunden',
  aboutExploreBody:
    'Wählen Sie einen Bereich und eine Nachricht und sehen Sie jedes Element, das sie enthalten kann: wie es heißt, was es laut offizieller ISO-20022-Definition bedeutet, welche Werte zulässig sind und welche Geschäftsregeln Felder verknüpfen. Fahren Sie mit der Maus über das i neben einer Bezeichnung für die Definition; „Spezifikation ansehen“ öffnet die offizielle Seite.',
  aboutCreateTitle: 'Eine neue Nachricht erstellen',
  aboutCreateBody:
    'Füllen Sie das Formular aus, um eine Nachricht von Grund auf zu erstellen. Ihre Eingaben werden beim Tippen geprüft, und die fertige Nachricht erscheint neben dem Formular als XML oder ISO-20022-JSON.',
  aboutSaveTitle: 'Speichern und später weitermachen',
  aboutSaveBody:
    'Speichern Sie Ihren Stand in einer Datei und laden Sie ihn jederzeit wieder, oder fügen Sie eine vorhandene Nachricht ein, um sie als Formular zu sehen. Alles bleibt in Ihrem Browser.',
  aboutIllustrateTitle: 'Abbildungen für Ihre Analysedokumente holen',
  aboutIllustrateBody:
    'Zoomen Sie auf den Teil einer Nachricht, über den Sie sprechen möchten, und machen Sie einen Screenshot des Formulars oder kopieren Sie dessen XML oder JSON in Ihr Dokument. In den Anzeigeeinstellungen wählen Sie Sprache, hell oder dunkel und Textgröße.',
  aboutBuildTitle: 'Diese Steuerelemente in Ihrer eigenen Anwendung verwenden',
  aboutBuildBody:
    'Gefällt Ihnen, wie das Formular aussieht und sich verhält? Wählen Sie unter dem Formular „Umsetzen!“ für eine Schritt-für-Schritt-Anleitung, um dieselben Steuerelemente in Ihre Anwendung einzubauen und nach Ihrem Geschmack zu gestalten.',
  aboutFootnote: 'Definitionen und Codelisten stammen aus dem ISO-20022-Repository. Der deutsche Text ist maschinell übersetzt und noch nicht geprüft.',
};
